name: ari_utils
description: Utility classes and functions I find myself using a lot. Specifically pythonic things.
version: 0.0.1
# homepage: https://github.com/SimpleTheory/ari_utils_dart

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  path: ^1.8.0
  collection: ^1.16.0
  quiver: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
